{{- if .Values.vault.enabled }}
{{ $vaConfig := (index .Values "vault-actions") }}
{{- if $vaConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $vaConfig.secretName }}
  labels: {{- include "nats-skeleton-spa.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ $vaConfig.hookConfiguration.hook }}
    "helm.sh/hook-weight": {{ (sub $vaConfig.hookConfiguration.hookWeight 1) | quote }}
    "helm.sh/hook-delete-policy": {{ $vaConfig.hookConfiguration.hookDeletePolicy }}
type: Opaque
stringData:
  vault-actions.yaml: |
    vault:
      url: {{ $.Values.vault.url }}
      token: {{ $vaConfig.bootstrapToken }}

    {{- with $vaConfig.config.bootstrap }}
    bootstrap:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    actions:
      - path: sys/policy/{{ $vaConfig.policyName }}
        type: write
        params:
          - k: policy
            v: |
              path "{{ $.Values.vault.nobodyAccount }}" {
                capabilities = ["read"]
              }

      - path: {{ $.Values.vault.authMount }}/role/{{ $.Values.vault.nobodyReaderRole }}
        type: write
        params:
          - {
              k: bound_service_account_names,
              v: {{ include "nats-skeleton-spa.serviceAccountName" . }}
            }
          - { k: bound_service_account_namespaces, v: {{ .Release.Namespace }} }
          - { k: policies, v: {{ $vaConfig.policyName }} }
          - { k: ttl, v: 1h }

    {{- range $vaConfig.config.additionalActions }}
      {{- toYaml . | nindent 6 }}
    {{- end }}

{{- end }}
{{- end }}
